version: '3.8'

services:

  api:
    build:
      context: .
      args:
        MONGO_DB_HOST: db
        MONGO_DB_PORT: 27017
        MONGO_DB_NAME: twitter
        MONGO_DB_USERNAME: root
        MONGO_DB_PASSWORD: root
        MONGO_DB_AUTH_NAME: admin
        ZIPKIN_BASE_URL: http://zipkin:9411/
    container_name: api-sre
    image: api-sre-twitter
    env_file:
      - ./api/container.env
    ports:
      - 8080:8080
    links:
      - db
      - zipkin
      - logstash
    depends_on:
      - db
      - zipkin
      - logstash

  db:
    container_name: db-sre
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  db-admin:
    container_name: dbui-sre
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 8081:8081
    depends_on:
      - db
    links:
      - db

  elasticsearch:
    container_name: elasticsearch-sre
    image: elasticsearch:7.7.1
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx512m -Xms512m
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft:  -1
        hard:  -1
    volumes:
      - ./monitoring/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  zipkin:
    container_name: zipkin-sre
    image: openzipkin/zipkin
    restart: always
    environment:
      ES_HOSTS: http://elasticsearch:9200
      STORAGE_TYPE: elasticsearch
    ports:
      - 9411:9411
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  logstash:
    container_name: logstash-sre
    image: logstash:7.7.1
    restart: always
    ports:
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./monitoring/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./monitoring/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    container_name: kibana-sre
    image: kibana:7.7.1
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./monitoring/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

  prometheus:
    container_name: prometheus-sre
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana-sre
    image: grafana/grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: sre
      GF_SECURITY_ADMIN_PASSWORD: sre
    ports:
      - 3000:3000
    links:
      - prometheus
    volumes:
    - ./monitoring/grafana/provisioning/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    - ./monitoring/grafana/provisioning/dashboard/sre-dashboard.yml:/etc/grafana/provisioning/dashboards/sre-dashboard.yml
    - ./monitoring/grafana/provisioning/dashboard/sre-dashboard.json:/var/lib/grafana/dashboards/sre-dashboard.json
